### ISSUE TITLE
as an affiliate, i want to earn rake from referrals

### ISSUE THREAD

**Issue by johannbarbie** [parsec-labs/acebusters-frontend#134]
<img width="779" alt="screen shot 2017-05-23 at 12 54 42 am" src="https://cloud.githubusercontent.com/assets/659301/26331685/80781f18-3f52-11e7-9f3e-308e94319db4.png">

connect the referral code field to the [backend API](https://github.com/acebusters/account-service/wiki).

**Comment by sunify** [comment]
Related to https://github.com/acebusters/contracts/issues/9

**Comment by sunify** [comment]
We do not have accounts anymore, so this stuff not actual anymore
