### ISSUE TITLE
As a player I want to see 'Deposit' pop-up instead of 'Insufficient funds' pop-up when I try to join the table with empty wallet

### ISSUE THREAD

**Issue by mateleshkavo** [parsec-labs/acebusters-frontend#694]
It's not really helpful to show 'Insufficient funds' pop-up when player tries to join the table. We can force people to deposit more by showing to them 'Deposit' pop-up instead.
'Deposit' pop-up should include my wallet address and some small instructions on how to deposit.
The same pop-up should appear if player loses all his money and tries to rebuy with empty wallet.
![deposit pop-up](https://user-images.githubusercontent.com/17405023/30843566-9d5ab160-a292-11e7-8914-8587cd667129.png)

**Comment by sunify** [comment]
Yeah, but deposit info it's not really helpful in this place. You can fund your wallet with ETH, but also you need to purchase some NTZ. Maybe will be better just place the link to deposit tab on the dashboard?

**Comment by mateleshkavo** [comment]
@sunify I would try to do something which will allow customers to deposit and play on this table without any redirects. But if we will not able to do so, probably we can just put a link there.
Anyway we definitely need to replace 'Insufficient funds' pop-up with something more meaningful.

**Comment by sunify** [comment]
@VonIobro what do you think?

**Comment by VonIobro** [comment]
I agree that more actionable info is needed for this modal.

Ideally the user would be given an interactive modal that would allow the deposit of ETH and then the automatic conversion of ETH to NTZ and then the user could automatically sit-in for the next hand. However there are two problems related to that. First the user would have to wait at least 2+ minutes for the two transactions to go through.

[ ] - If the user has ETH in their account already && if ETH to NTZ  min exchange >= table min buy-in... 
  * Show ETH > NTZ Exchange Dialog
  * Allow user to exchange ETH for NTZ
  * Allow user to sit-in at table

[ ] - If the user does not have ETH, at minimum the modal can provide: 
  * instructions: 1. deposit ETH 2. convert ETH > NTZ
  * a link to 
    * standup from table
    * redirect to their dashboard and the 'wallet' tab to display their ETH address
  * (Given support for NTZ on Changelly/ShapeShift, the above would be replaced by their widget)

Additionally the table join modal could give further information, such as a warning that they are running low on NTZ.

**Comment by VonIobro** [comment]
Closing, as this does not align with our current demonstration model.
