### ISSUE TITLE
Address issue

### ISSUE THREAD

**Issue by hisssssssssssssssssssssssssssssssss** [parsec-labs/acebusters-frontend#873]
Hi, you are offering my refund to my metamask account. Can you refund direct to the account that made the purchase instead please? It should be straight forward to track it from the original purchase address here:

0xED2f3273e71f726d6495a64364a69Ed1AE792A7f

To quote your email to me:

You ETH amount: 0.5058
Your Metamask address: 0x14c46b50e04b6859c0f7f1b91f5eb8abe234861f

Hope that helps, cna you transact now and reply for me here so I know it’s in the way please

Thanks and good luck with future endeavours

**Comment by johannbarbie** [comment]
i can see in the block explorer that `0xED2f3273e71f726d6495a64364a69Ed1AE792A7f` funded `0x14c46b50e04b6859c0f7f1b91f5eb8abe234861f` in [this tx](https://etherscan.io/tx/0xc65ef16bdf8ab9ab4c2a00bc120687064f3432047b703fcf96b22ceccbeb8d1b). unfortunately that doesn't prove ownership by the same person. could you sign a message with the private key of `0x14c46b50e04b6859c0f7f1b91f5eb8abe234861f`, for example this one: `refundtoED2f`.
then i could update refund destination easily.

**Comment by hisssssssssssssssssssssssssssssssss** [comment]
Hi,

Sorry am quite a novice. This is not straight forward for me. I am having problems logging in to my metamask which is why I requested back to the originating wallet as you can see this wallet was only set up and used for Acebusters. Is there anything else I can do to make you comfortable with the transaction short of panicinking to get metamask working after the update in December?

Regards
Simon Wentworth
Whatsapp: +44 7903 032 534
Tel: +44 7398 212 297

**Comment by johannbarbie** [comment]
verified by sending another email

**Comment by hisssssssssssssssssssssssssssssssss** [comment]
Safely received

Many thanks

Good luck with future ventures and save my details please and let me know when you are ready to go again!

Regards
Simon Wentworth
Whatsapp: +44 7903 032 534
Tel: +44 7398 212 297
