### ISSUE TITLE
add initial login notification "dismissable" with link to blog

### ISSUE THREAD

**Issue by johannbarbie** [parsec-labs/acebusters-frontend#875]
the blog article should explain what we are doing with acebusters

**Comment by johannbarbie** [comment]
https://www.acebusters.com/blog/the-acebusters-crowdsale-has-ended

**Comment by VonIobro** [comment]
Actually in the lobby there is now a message that poses the question, "I invested into the Acebusters ICO, but it did not succeed. How to refund?". I think we should just add the blog link to that answer. Who maintains that? @johannbarbie

**Comment by troggy** [comment]
@VonIobro +1

I think the message is sourced from Prismic

**Comment by sunify** [comment]
I updated lobby message. Closing the issue
