### ISSUE TITLE
As a user I want to be able to request more play chips

### ISSUE THREAD

**Issue by mateleshkavo** [parsec-labs/acebusters-frontend#883]
As a new customer, I want to be able to request more play chips when I have lost all chips on the account (NTZ and ETH). 

There should be a limitation for such requests - once per hour.

**Comment by VonIobro** [comment]
As the goal of the poker front-end is for demonstration, and that there is very little friction for creating a new account, that the user should just 'log-out' and then create a new account, which will automatically give them free chips. I am building this functionality into PR #880.

**Comment by troggy** [comment]
alternatively we can create a super-simple UI-less faucet to get playing chips (time restricted). So not too spend to much time on creating UI for this is relevant only for demo.

**Comment by sunify** [comment]
Actually, we can just resend funds request when player's balance lower than 100NTZ for example. It will fill balance up to 1000NTZ and 0.1ETH https://github.com/parsec-labs/account-service/pull/24/files#diff-1fdf421c05c1140f6d71444ea2b27638R420

**Comment by sunify** [comment]
Implemented in #872
