### ISSUE TITLE
Clean dashboard - Wallet

### ISSUE THREAD

**Issue by sunify** [parsec-labs/acebusters-frontend#889]
I think we don't need Wallet tab anymore. Also, we have a ton of unused code in Dashboard component and container

- [x] wallet
- [x] exchange
- [x] Invest: PowerUp, PowerDown
- [x] Economy Info
- [x] SectionReceive, DepositInfo
- [x] Fish/Shark Warning, AccountProgress

**Comment by VonIobro** [comment]
I will create seperate issues for the other legacy Dashboard components
