### ISSUE TITLE
Seperate txnsToList

### ISSUE THREAD

**Issue by VonIobro** [parsec-labs/acebusters-frontend#895]
- [ ] seperate into container and component
- [ ] move styles from container folder to component folder

**Comment by sunify** [comment]
What do you mean?

**Comment by VonIobro** [comment]
Mostly just code optimization, this issue could be dropped. But I figured since we were overhauling it anyways...

**Comment by sunify** [comment]
I don't mind about refactoring, I'm just not sure about this one. What component and container do you want to extract? TransactionHistory?
