### ISSUE TITLE
Lobby page loads for more than 2 minutes in the Chrome

### ISSUE THREAD

**Issue by mateleshkavo** [parsec-labs/acebusters-frontend#899]
Lobby page after hard refresh takes to load around 2 minutes.

![pageload](https://user-images.githubusercontent.com/17405023/36208657-48ef75f0-11a2-11e8-9bd9-0538f9d36403.png)

**Comment by sunify** [comment]
gzip compression was disabled. I enabled it, so now page loads much faster.

@mateleshkavo check plz

**Comment by mateleshkavo** [comment]
@sunify Much better now.

**Comment by sunify** [comment]
Cool, I'm closing the issue
