### ISSUE TITLE
ETH transaction is not being reflected in History

### ISSUE THREAD

**Issue by mateleshkavo** [parsec-labs/acebusters-frontend#900]
When user account is being charged with ETH, that transactions is not being reflected in transaction history.

![2018-02-14_0818](https://user-images.githubusercontent.com/17405023/36208869-d9c6b4c6-11a2-11e8-9ce5-2468f8e7e265.png)

**Comment by sunify** [comment]
It's much harder to show such transactions in history now. I don't think this effort worth it
